name: learn-github-actions
on: 
  push:
    branches:
      main
jobs:
  upload-artifact-and-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm i -D cowsay
      - run: npx cowsay `date`>hello.txt
      - uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: .

